host: '127.0.0.1'
port: 8080

ffmpeg-path: ''

database: ./db/User.db

mediafolder: ./core/resources/

platforms:
  kugou:
    fetcher: KuGou
    
  kuwo:
    fetcher: KuWo
    
  migu:
    fetcher: MiGu
    
  qq:
    fetcher: QQ
    
  wangyi:
    fetcher: WangYi
    